### ISSUE TITLE
Optionally a separate zoom image

### ISSUE THREAD

**Issue by pacosegovia** [Intera/vue-zoom-on-hover#1]
What is the way to zoom with the separate image?

Thanks

**Comment by jkalbhenn** [comment]
specifying the full size image with the attribute `img-zoom` should work. it should then use the bigger image when zooming.
```
<zoom-on-hover img-normal="image.jpg" img-zoom="bigger-image.jpg"></zoom-on-hover>
```

**Comment by pacosegovia** [comment]
Ok, thanks!
