### ISSUE TITLE
Put it on npm

### ISSUE THREAD

**Issue by thukuwanjiku** [Intera/vue-zoom-on-hover#2]
Can you please put it on npm so that it is installable via npm. I'm using .vue file and including it in link and script tags as you have (demo/main.html) isn't working. It logs an error zoomOnHover is not defined

**Comment by ghost** [comment]
i second this, would be easier if it was on npm

**Comment by astehlik** [comment]
Hi,

the package is now available on npm:

https://www.npmjs.com/package/@intera/vue-zoom-on-hover

Please let us know, if you experience any problems.

Cheers,
Alex
