### ISSUE TITLE
Poor docs, how to add it as a component ?

### ISSUE THREAD

**Issue by marwan2** [Intera/vue-zoom-on-hover#4]
How to use it inside Laravel VUE App ?
How to install it ?
How to use it in another component page ?

Many questions you should answer !!!

**Comment by quevlu** [comment]
@marwan2 Hello my friend, i take a few minutes to solve this issue. The component in vue is the next :

https://pastebin.com/H6dZBxhj

![image](https://user-images.githubusercontent.com/2734741/64661795-7c3c2500-d41c-11e9-9724-75a184e622a7.png)

**Comment by marwan2** [comment]
Thanks @byinff, it works

**Comment by jkalbhenn** [comment]
good point. i will try to address this in the readme with the next update.

**Comment by jkalbhenn** [comment]
i added information about installation and usage as a component to the readme. it is not necessary to extract the code into a .vue file. i dont know how to use it inside a laravel app. thanks for the report.
