### ISSUE TITLE
This is setting styles directly and manually

### ISSUE THREAD

**Issue by goltsov** [Intera/vue-zoom-on-hover#5]
https://github.com/Intera/vue-zoom-on-hover/blob/b22bf28523b6b42a4d482ca7f9467ef2759394b4/zoomOnHover.js#L35

I recommend adding a zoomed-in state and using that to toggle a css class to change opacity of the two images.

**Comment by jkalbhenn** [comment]
if i understand correctly, this would allow more control with css. i'll look into it with the next feature addition.

**Comment by jkalbhenn** [comment]
this has been implemented. zoomed state is now handled via a property "this.zoomed = true" and a css class. thanks for the report.
