### ISSUE TITLE
My strange situation with max-width: 100%

### ISSUE THREAD

**Issue by shoha-kh** [Intera/vue-zoom-on-hover#7]
Hello everyone, just want to share with the problem that I had and this is my mistake of inattention...
I connected the plugin to the project I'm already working on, and the plugin just did not work so that it did not do and the problem turns out to be in css max-width: 100%;.
I'm writing this because there might be some poor people like me who can't figure it out.

Sorry in advance for my English. ))

**Comment by jkalbhenn** [comment]
hi, no problem. maybe i can add a clearer note to the readme in the future. was the max-width on the <zoom-on-hover> parent element?

**Comment by shoha-kh** [comment]
I had max-width on all img's this may seem strange, but it solves problems with huge pictures that come out of the content))
`img {
  max-width: 100%;
}`

Solved the problem this way
`.zoom-on-hover .zoom {
    max-width: none;
}`
