### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by matinwd** [Intera/vue-zoom-on-hover#8]
```
import PicZoom from 'vue-piczoom'
    import zoomOnHover from 'vue-zoom-on-hover'

    export default {
        name: 'app',
        components: {
            PicZoom,zoomOnHover
        },
}
```
shows this error in console.
[Vue warn]: Failed to mount component: template or render function not defined.

this is my template
<div style="width:400px">
                        <zoom-on-hover :img-normal="require('../assets/body/product/imac2.jpg')"></zoom-on-hover>
                    </div>

**Comment by jkalbhenn** [comment]
vue-zoom-on-hover is not a module but only a javascript file to be included.
maybe `import './vue-zoom-on-hover'` will work.

**Comment by matinwd** [comment]
u mean like this?

`    import  'vue-zoom-on-hover'`
so how can i use it as a zoomOnHover component? console says 
`ReferenceError: zoomOnHover is not defined`

**Comment by jkalbhenn** [comment]
yes, like this or with the "./" maybe, i've read that it might be required, couldnt test it right now.
can you include zoomOnHover.js before your code in the html? that is how it is supposed to be included. like with a script tag: `<script type="text/javascript" src="zoomOnHover.js"></script>`

**Comment by chrisjung-dev** [comment]
Seems there is a default export missing.

**Comment by matinwd** [comment]
i added script but how vue can register this component without exporting it? 
still does not work

**Comment by jkalbhenn** [comment]
any `import` for the component should be removed. a global variable is set when the component code is loaded with the script tag.
~~~
var zoomOnHover = {
~~~
you can see an example of how it is then used in the code for the demo [here](https://github.com/Intera/vue-zoom-on-hover/blob/master/demo/main.html) - there is a script-tag loading the plugin, and in another script at the bottom the component is used. i checked that it works with the newest vue.js version.

what build of vue.js are you using? there are at least two: a runtime only build and a full build. described [here](https://vuejs.org/v2/guide/installation.html). the runtime only build doesnt process "template:" options, which could be the cause for the error you are seeing.

**Comment by jkalbhenn** [comment]
were you able to make any progress with this?

**Comment by jkalbhenn** [comment]
closed because of inactivity.
